# -*- coding: utf-8 -*-
"""classificar_imagens.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HNeU-vf5fECyWJ8vf08ZVIRRGBsUiX6Z
"""

import tensorflow
from tensorflow import keras
import numpy as np

(x_train, y_train), (x_test, y_test) = keras.datasets.fashion_mnist.load_data()
assert x_train.shape == (60000, 28, 28)
assert x_test.shape == (10000, 28, 28)
assert y_train.shape == (60000,)
assert y_test.shape == (10000,)
import matplotlib.pyplot as plt
nomes_de_classificacoes = ['T-shirt/top',
'Trouser',
'Pullover',
'Dress',
'Coat',
'Sandal',
'Shirt',
'Sneaker',
'Bag',
'Ankle boot']

modelo = keras.Sequential([ 
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(256, activation=tensorflow.nn.relu),
    keras.layers.Dense(10, activation=tensorflow.nn.softmax)
])

modelo.compile(optimizer='adam', 
               loss='sparse_categorical_crossentropy',
               metrics= ['accuracy'])

historico = modelo.fit(x_train, y_train, epochs = 30, validation_split=0.2)

plt.plot(historico.history['accuracy'])
plt.plot(historico.history['val_accuracy'])
plt.title('Acuracia por épocas')
plt.xlabel('Épocas')
plt.ylabel('Acuracia')
plt.legend(['treino', 'validação'])

plt.plot(historico.history['loss'])
plt.plot(historico.history['val_loss'])
plt.title('Perda por épocas')
plt.xlabel('Épocas')
plt.ylabel('Perda')
plt.legend(['treino', 'validação'])

testes = modelo.predict(x_test)
print('resultado do teste', np.argmax(testes[0]))
print('resultado do teste', y_test[0])

perda_teste, acuracia_teste = modelo.evaluate(x_test, y_test)
print('perda do teste', perda_teste)
print('acuracia do teste', acuracia_teste)